# Navegação entre painéis
unbind -n C-Left
bind-key -n C-M-Left select-pane -L

# Mapeamentos para Home e End
bind-key -n Home send-keys \033OH
bind-key -n End send-keys \033OF

# Mapeamento para Ctrl+Home e Ctrl+End (início/fim do buffer inteiro)
bind-key -n C-Home send-keys "\033[1;5H"
bind-key -n C-End send-keys "\033[1;5F"

# Navegação no histórico com PageUp/PageDown
bind-key -n PageUp copy-mode -u \   ; send-keys PageUp
bind-key -n PageDown copy-mode -d \ ; send-keys PageDown

# Apaga a linha inteira
bind-key -n S-Delete send-keys C-u
